module.exports = {
  docsSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'guide',
    },
    {
      type: 'autogenerated',
      dirName: 'dev',
    },
    {
      type: 'autogenerated',
      dirName: 'contracts',
    },
    {
      type: 'autogenerated',
      dirName: 'security',
    },
  ],
};
